name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. openjij@j-ij.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: Python-Version
    attributes:
      label: Python Version
      description: What python version of our software are you running?
      options:
        - 3.7
        - 3.8 
        - 3.9 
        - 3.10
    validations:
      required: true
  - type: dropdown
    id: OS
    attributes:
      label: What os are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - MacOS
        - Windows
    validations:
      required: true
      
  - type: dropdown
    id: arch
    attributes:
      label: What arch are you seeing the problem on?
      multiple: true
      options:
        - x86_64
        - aarch64
        - x86
    
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
