cimod: cimod::BinaryQuadraticModel< IndexType, FloatType, Dict > Class Template Reference
cimod::BinaryQuadraticModel< IndexType, FloatType, Dict > Class Template Reference
Class for legacy binary quadratic model (dict datastructure).
#include <binary_quadratic_model_dict.hpp>
Public Types
using DenseMatrix = Eigen::Matrix< FloatType, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor >
using SparseMatrix = Eigen::SparseMatrix< FloatType, Eigen::RowMajor >
using Matrix = Eigen::Matrix< FloatType, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor >
Eigen Matrix.
using json = nlohmann::json
Public Member Functions
BinaryQuadraticModel (const Linear< IndexType, FloatType > &linear, const Quadratic< IndexType, FloatType > &quadratic, const FloatType &offset, const Vartype vartype)
BinaryQuadraticModel constructor.
BinaryQuadraticModel (const Linear< IndexType, FloatType > &linear, const Quadratic< IndexType, FloatType > &quadratic, const Vartype vartype)
BinaryQuadraticModel constructor.
BinaryQuadraticModel (const Eigen::Ref< const DenseMatrix > &, const std::vector< IndexType > &, const FloatType &, const Vartype, bool)
BinaryQuadraticModel constructor (with matrix); This constructor is not be implemented.
BinaryQuadraticModel (const Eigen::Ref< const DenseMatrix > &, const std::vector< IndexType > &, const Vartype, bool)
BinaryQuadraticModel constructor (with matrix); This constructor is not be implemented.
BinaryQuadraticModel (const SparseMatrix &, const std::vector< IndexType > &, const FloatType &, const Vartype)
BinaryQuadraticModel constructor (with sparse matrix); this constructor is for developers.
BinaryQuadraticModel (const SparseMatrix &, const std::vector< IndexType > &, const Vartype)
BinaryQuadraticModel constructor (with sparse matrix); this constructor is for developers.
BinaryQuadraticModel (const BinaryQuadraticModel &)=default
Copy constructor of BinaryQuadraticModel.
std::vector< IndexType > _generate_indices () const
generate indices
size_t length () const
Return the number of variables.
size_t get_num_variables () const
Return the number of variables.
bool contains (const IndexType &v) const
Return true if the variable contains v.
FloatType get_linear (IndexType label_i) const
Get the element of linear object.
const Linear< IndexType, FloatType > & get_linear () const
Get the linear object.
FloatType get_quadratic (IndexType label_i, IndexType label_j) const
Get the element of quadratic object.
const Quadratic< IndexType, FloatType > & get_quadratic () const
Get the quadratic object.
const FloatType & get_offset () const
Get the offset.
const Vartype & get_vartype () const
Get the vartype object.
const std::vector< IndexType > get_variables () const
Get variables.
BinaryQuadraticModel< IndexType, FloatType, DataType > empty (Vartype vartype)
Create an empty BinaryQuadraticModel.
void add_variable (const IndexType &v, const FloatType &bias)
Add variable v and/or its bias to a binary quadratic model.
void add_variables_from (const Linear< IndexType, FloatType > &linear)
Add variables and/or linear biases to a binary quadratic model.
void add_interaction (const IndexType &arg_u, const IndexType &arg_v, const FloatType &bias)
Add an interaction and/or quadratic bias to a binary quadratic model.
void add_interactions_from (const Quadratic< IndexType, FloatType > &quadratic)
Add interactions and/or quadratic biases to a binary quadratic model.
void remove_variable (const IndexType &v)
Remove variable v and all its interactions from a binary quadratic model.
void remove_variables_from (const std::vector< IndexType > &variables)
Remove specified variables and all of their interactions from a binary quadratic model.
void remove_interaction (const IndexType &arg_u, const IndexType &arg_v)
Remove interaction of variables u, v from a binary quadratic model.
void remove_interactions_from (const std::vector< std::pair< IndexType, IndexType >> &interactions)
Remove all specified interactions from the binary quadratic model.
void add_offset (const FloatType &offset)
Add specified value to the offset of a binary quadratic model.
void remove_offset ()
Set the binary quadratic model's offset to zero.
void scale (const FloatType &scalar, const std::vector< IndexType > &ignored_variables={}, const std::vector< std::pair< IndexType, IndexType >> &ignored_interactions={}, const bool ignored_offset=false)
Multiply by the specified scalar all the biases and offset of a binary quadratic model.
void normalize (const std::pair< FloatType, FloatType > &bias_range={ 1.0, 1.0 }, const bool use_quadratic_range=false, const std::pair< FloatType, FloatType > &quadratic_range={ 1.0, 1.0 }, const std::vector< IndexType > &ignored_variables={}, const std::vector< std::pair< IndexType, IndexType >> &ignored_interactions={}, const bool ignored_offset=false)
Normalizes the biases of the binary quadratic model such that they fall in the provided range(s), and adjusts the offset appropriately.
void fix_variable (const IndexType &v, const int32_t &value)
Fix the value of a variable and remove it from a binary quadratic model.
void fix_variables (const std::vector< std::pair< IndexType, int32_t >> &fixed)
Fix the value of the variables and remove it from a binary quadratic model.
void flip_variable (const IndexType &v)
Flip variable v in a binary quadratic model.
void contract_variables (const IndexType &u, const IndexType &v)
Enforce u, v being the same variable in a binary quadratic model.
void change_vartype (const Vartype &vartype)
Create a binary quadratic model with the specified vartype.
BinaryQuadraticModel change_vartype (const Vartype &vartype, bool inplace)
Create a binary quadratic model with the specified vartype.
FloatType energy (const Sample< IndexType > &sample) const
Determine the energy of the specified sample of a binary quadratic model.
std::vector< FloatType > energies (const std::vector< Sample< IndexType >> &samples_like) const
Determine the energies of the given samples.
std::tuple< Quadratic< IndexType, FloatType >, FloatType > to_qubo ()
Convert a binary quadratic model to QUBO format.
std::tuple< Linear< IndexType, FloatType >, Quadratic< IndexType, FloatType >, FloatType > to_ising ()
Convert a binary quadratic model to Ising format.
Matrix interaction_matrix (const std::vector< IndexType > &indices) const
generate interaction matrix with given list of indices The generated matrix will be the following symmetric matrix:
Matrix interaction_matrix () const
generate interaction matrix with given list of indices The generated matrix will be the following symmetric matrix:
json to_serializable () const
Convert the binary quadratic model to a serializable object user_bytes is assume to be set to False.
Static Public Member Functions
static std::tuple< Linear< IndexType, FloatType >, Quadratic< IndexType, FloatType >, FloatType > spin_to_binary (const Linear< IndexType, FloatType > &linear, const Quadratic< IndexType, FloatType > &quadratic, const FloatType &offset)
Convert linear, quadratic, and offset from spin to binary.
static std::tuple< Linear< IndexType, FloatType >, Quadratic< IndexType, FloatType >, FloatType > binary_to_spin (const Linear< IndexType, FloatType > &linear, const Quadratic< IndexType, FloatType > &quadratic, const FloatType &offset)
Convert linear, quadratic and offset from binary to spin.
static BinaryQuadraticModel from_qubo (const Quadratic< IndexType, FloatType > &Q, FloatType offset=0.0)
Create a binary quadratic model from a QUBO model.
static BinaryQuadraticModel from_ising (const Linear< IndexType, FloatType > &linear, const Quadratic< IndexType, FloatType > &quadratic, FloatType offset=0.0)
Create a binary quadratic model from an Ising problem.
template<typename IndexType_serial = IndexType, typename FloatType_serial = FloatType>
static BinaryQuadraticModel< IndexType_serial, FloatType_serial, DataType > from_serializable (const json &input)
Create a BinaryQuadraticModel instance from a serializable object.
Protected Attributes
Linear< IndexType, FloatType > m_linear
Linear biases as a dictionary.
Quadratic< IndexType, FloatType > m_quadratic
Quadratic biases as a dictionary.
FloatType m_offset
The energy offset associated with the model.
Vartype m_vartype = Vartype::NONE
The model's type.
Private Types
using DataType = Dict
Detailed Description
template<typename IndexType, typename FloatType>
class cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >
Class for legacy binary quadratic model (dict datastructure).
Member Typedef Documentation
DataType
template<typename IndexType , typename FloatType > using cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::DataType = Dict private
DenseMatrix
template<typename IndexType , typename FloatType > using cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::DenseMatrix = Eigen::Matrix<FloatType, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>
json
template<typename IndexType , typename FloatType > using cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::json = nlohmann::json
Matrix
template<typename IndexType , typename FloatType > using cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::Matrix = Eigen::Matrix<FloatType, Eigen::Dynamic, Eigen::Dynamic, Eigen::RowMajor>
Eigen Matrix.
SparseMatrix
template<typename IndexType , typename FloatType > using cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::SparseMatrix = Eigen::SparseMatrix<FloatType, Eigen::RowMajor>
Constructor & Destructor Documentation
BinaryQuadraticModel() [1/7]
template<typename IndexType , typename FloatType > cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::BinaryQuadraticModel (const Linear< IndexType, FloatType > & linear, const Quadratic< IndexType, FloatType > & quadratic, const FloatType & offset, const Vartype vartype) inline
BinaryQuadraticModel constructor.
Parameters
linear
quadratic
offset
vartype
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_interactions_from(), and cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_variables_from().
BinaryQuadraticModel() [2/7]
template<typename IndexType , typename FloatType > cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::BinaryQuadraticModel (const Linear< IndexType, FloatType > & linear, const Quadratic< IndexType, FloatType > & quadratic, const Vartype vartype) inline
BinaryQuadraticModel constructor.
Parameters
linear
quadratic
vartype
BinaryQuadraticModel() [3/7]
template<typename IndexType , typename FloatType > cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::BinaryQuadraticModel (const Eigen::Ref< const DenseMatrix > & , const std::vector< IndexType > & , const FloatType & , const Vartype, bool) inline
BinaryQuadraticModel constructor (with matrix); This constructor is not be implemented.
Parameters
mat
labels_vec
offset
vartype
BinaryQuadraticModel() [4/7]
template<typename IndexType , typename FloatType > cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::BinaryQuadraticModel (const Eigen::Ref< const DenseMatrix > & , const std::vector< IndexType > & , const Vartype, bool) inline
BinaryQuadraticModel constructor (with matrix); This constructor is not be implemented.
Parameters
mat
labels_vec
vartype
BinaryQuadraticModel() [5/7]
template<typename IndexType , typename FloatType > cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::BinaryQuadraticModel (const SparseMatrix & , const std::vector< IndexType > & , const FloatType & , const Vartype) inline
BinaryQuadraticModel constructor (with sparse matrix); this constructor is for developers.
Parameters
mat
labels_vec
offset
vartype
BinaryQuadraticModel() [6/7]
template<typename IndexType , typename FloatType > cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::BinaryQuadraticModel (const SparseMatrix & , const std::vector< IndexType > & , const Vartype) inline
BinaryQuadraticModel constructor (with sparse matrix); this constructor is for developers.
Parameters
mat
labels_vec
vartype
BinaryQuadraticModel() [7/7]
template<typename IndexType , typename FloatType > cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::BinaryQuadraticModel (const BinaryQuadraticModel< IndexType, FloatType, Dict > &) default
Copy constructor of BinaryQuadraticModel.
Parameters
bqm
Member Function Documentation
_generate_indices()
template<typename IndexType , typename FloatType > std::vector<IndexType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::_generate_indices () const inline
generate indices
Returns
generated indices
add_interaction()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::add_interaction (const IndexType & arg_u, const IndexType & arg_v, const FloatType & bias) inline
Add an interaction and/or quadratic bias to a binary quadratic model.
Parameters
arg_u
arg_v
bias
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_offset(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_variable(), cimod::BINARY, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_vartype(), cimod::insert_or_assign(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_vartype, cimod::NONE, cimod::SPIN, and cimod.model.legacy.binary_quadratic_model::vartype.
add_interactions_from()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::add_interactions_from (const Quadratic< IndexType, FloatType > & quadratic) inline
Add interactions and/or quadratic biases to a binary quadratic model.
Parameters
quadratic
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_interaction().
add_offset()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::add_offset (const FloatType & offset) inline
Add specified value to the offset of a binary quadratic model.
Parameters
offset
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_offset.
add_variable()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::add_variable (const IndexType & v, const FloatType & bias) inline
Add variable v and/or its bias to a binary quadratic model.
Parameters
v
bias
References cimod::BINARY, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_vartype(), cimod::insert_or_assign(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_offset, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_vartype, cimod::NONE, cimod::SPIN, and cimod.model.legacy.binary_quadratic_model::vartype.
add_variables_from()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::add_variables_from (const Linear< IndexType, FloatType > & linear) inline
Add variables and/or linear biases to a binary quadratic model.
Parameters
linear
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_variable().
binary_to_spin()
template<typename IndexType , typename FloatType > static std::tuple<Linear<IndexType, FloatType>, Quadratic<IndexType, FloatType>, FloatType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::binary_to_spin (const Linear< IndexType, FloatType > & linear, const Quadratic< IndexType, FloatType > & quadratic, const FloatType & offset) inline static
Convert linear, quadratic and offset from binary to spin.
Does no checking of vartype. Copies all of the values into new objects.
Parameters
linear
quadratic
offset
Returns
A tuple including a linear bias, a quadratic bias and an offset.
References cimod::insert_or_assign().
change_vartype() [1/2]
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::change_vartype (const Vartype & vartype) inline
Create a binary quadratic model with the specified vartype.
This function does not return any object.
Parameters
vartype
References cimod::BINARY, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_offset, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_vartype, cimod::SPIN, and cimod.model.legacy.binary_quadratic_model::vartype.
change_vartype() [2/2]
template<typename IndexType , typename FloatType > BinaryQuadraticModel cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::change_vartype (const Vartype & vartype, bool inplace) inline
Create a binary quadratic model with the specified vartype.
Parameters
vartype
inplace
Returns
A new instance of the BinaryQuadraticModel class.
References cimod::BINARY, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_linear(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_offset(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_quadratic(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_vartype(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_offset, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_vartype, cimod::SPIN, and cimod.model.legacy.binary_quadratic_model::vartype.
contains()
template<typename IndexType , typename FloatType > bool cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::contains (const IndexType & v) const inline
Return true if the variable contains v.
Returns
Return true if the variable contains v.
Parameters
v
contract_variables()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::contract_variables (const IndexType & u, const IndexType & v) inline
Enforce u, v being the same variable in a binary quadratic model.
Parameters
u
v
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_interaction(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_offset(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_variable(), cimod::BINARY, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_vartype, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::remove_interaction(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::remove_interactions_from(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::remove_variable(), and cimod::SPIN.
empty()
template<typename IndexType , typename FloatType > BinaryQuadraticModel<IndexType, FloatType, DataType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::empty (Vartype vartype) inline
Create an empty BinaryQuadraticModel.
References cimod.model.legacy.binary_quadratic_model::vartype.
energies()
template<typename IndexType , typename FloatType > std::vector<FloatType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::energies (const std::vector< Sample< IndexType >> & samples_like) const inline
Determine the energies of the given samples.
Parameters
samples_like
Returns
A vector including energies with respect to the samples.
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::energy().
energy()
template<typename IndexType , typename FloatType > FloatType cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::energy (const Sample< IndexType > & sample) const inline
Determine the energy of the specified sample of a binary quadratic model.
Parameters
sample
Returns
An energy with respect to the sample.
References cimod::check_vartype(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_offset, and cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_vartype.
fix_variable()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::fix_variable (const IndexType & v, const int32_t & value) inline
Fix the value of a variable and remove it from a binary quadratic model.
Parameters
v
value
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_offset(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_variable(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::remove_interactions_from(), and cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::remove_variable().
fix_variables()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::fix_variables (const std::vector< std::pair< IndexType, int32_t >> & fixed) inline
Fix the value of the variables and remove it from a binary quadratic model.
Parameters
fixed
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::fix_variable().
flip_variable()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::flip_variable (const IndexType & v) inline
Flip variable v in a binary quadratic model.
Parameters
v
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_offset(), cimod::BINARY, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_vartype, and cimod::SPIN.
from_ising()
template<typename IndexType , typename FloatType > static BinaryQuadraticModel cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::from_ising (const Linear< IndexType, FloatType > & linear, const Quadratic< IndexType, FloatType > & quadratic, FloatType offset = 0.0) inline static
Create a binary quadratic model from an Ising problem.
Parameters
linear
quadratic
offset
Returns
Binary quadratic model with vartype set to .Vartype.SPIN.
References cimod::SPIN.
from_qubo()
template<typename IndexType , typename FloatType > static BinaryQuadraticModel cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::from_qubo (const Quadratic< IndexType, FloatType > & Q, FloatType offset = 0.0) inline static
Create a binary quadratic model from a QUBO model.
Parameters
Q
offset
Returns
Binary quadratic model with vartype set to .Vartype.BINARY.
References cimod::BINARY.
from_serializable()
template<typename IndexType , typename FloatType > template<typename IndexType_serial = IndexType, typename FloatType_serial = FloatType> static BinaryQuadraticModel<IndexType_serial, FloatType_serial, DataType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::from_serializable (const json & input) inline static
Create a BinaryQuadraticModel instance from a serializable object.
Template Parameters
IndexType_serial
FloatType_serial
Parameters
input
Returns
BinaryQuadraticModel<IndexType_serial, FloatType_serial, DataType>
References cimod::BINARY, cimod::insert_or_assign(), cimod::SPIN, and cimod.model.legacy.binary_quadratic_model::vartype.
get_linear() [1/2]
template<typename IndexType , typename FloatType > const Linear<IndexType, FloatType>& cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::get_linear () const inline
Get the linear object.
Returns
A linear bias.
get_linear() [2/2]
template<typename IndexType , typename FloatType > FloatType cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::get_linear (IndexType label_i) const inline
Get the element of linear object.
Parameters
label_i
Returns
get_num_variables()
template<typename IndexType , typename FloatType > size_t cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::get_num_variables () const inline
Return the number of variables.
Deprecated:
use get_num_variables.
Returns
The number of variables.
get_offset()
template<typename IndexType , typename FloatType > const FloatType& cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::get_offset () const inline
Get the offset.
Returns
An offset.
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_offset.
get_quadratic() [1/2]
template<typename IndexType , typename FloatType > const Quadratic<IndexType, FloatType>& cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::get_quadratic () const inline
Get the quadratic object.
Returns
A quadratic bias.
get_quadratic() [2/2]
template<typename IndexType , typename FloatType > FloatType cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::get_quadratic (IndexType label_i, IndexType label_j) const inline
Get the element of quadratic object.
Returns
A quadratic bias.
get_variables()
template<typename IndexType , typename FloatType > const std::vector<IndexType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::get_variables () const inline
Get variables.
Returns
variables
get_vartype()
template<typename IndexType , typename FloatType > const Vartype& cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::get_vartype () const inline
Get the vartype object.
Returns
Type of the model.
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_vartype.
interaction_matrix() [1/2]
template<typename IndexType , typename FloatType > Matrix cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::interaction_matrix () const inline
generate interaction matrix with given list of indices The generated matrix will be the following symmetric matrix:
\[ \begin{pmatrix} J_{0,0} & J_{0,1} & \cdots & J_{0,N-1} & h_{0}\\ 0 & J_{1,1} & \cdots & J_{1,N-1} & h_{1}\\ \vdots & \vdots & \vdots & \vdots & \vdots \\ 0 & 0 & \cdots & J_{N-1,N-1} & h_{N-1}\\ 0 & 0 & \cdots & 0 & 1 \\ \end{pmatrix} \]
References cimod.model.legacy.binary_quadratic_model::_interaction_matrix, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_num_variables(), and cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_variables().
interaction_matrix() [2/2]
template<typename IndexType , typename FloatType > Matrix cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::interaction_matrix (const std::vector< IndexType > & indices) const inline
generate interaction matrix with given list of indices The generated matrix will be the following symmetric matrix:
\[ \begin{pmatrix} \tilde{J}_{0,0} & \tilde{J}_{0,1} & \tilde{J}_{0,2} & \cdots \\ \tilde{J}_{1,0} & \tilde{J}_{1,1} & \tilde{J}_{1,2} & \cdots \\ \tilde{J}_{2,0} & \tilde{J}_{2,1} & \tilde{J}_{2,2} & \cdots \\ \vdots & \vdots & \vdots & \ddots \\ \end{pmatrix} \]
where in the Ising case,
\[ \tilde{J}_{f(i),f(j)} = J_{ij} + J_{ji}, \\ \tilde{J}_{f(i),f(i)} = h_{i}, \]
and the QUBO case,
\[ \tilde{J}_{f(i),f(j)} = Q_{ij} + Q_{ji}, \\ \tilde{J}_{f(i),f(i)} = Q_{ii}, \]
and the function \(f\) denotes a mapping from index to the corresponding number specified by the argument indices. For instance, if indices is ['a', 'b', 'c'], The following equations, \(f(a) = 0, f(b)=1, \mathrm{and} f(c)=2\) hold.
The original Hamiltonian can be rewritten with \(\tilde{J_{ij}}\) as
\[ E_{\mathrm{Ising}} = \sum_{i} \tilde{J}_{f(i),f(i)} s_i + \sum_{i < j} \tilde{J}_{f(i), f(j)} s_i s_j + \delta_{\mathrm{Ising}}, \]
and
\[ E_{\mathrm{QUBO}} = \sum_{i} \tilde{J}_{f(i), f(i)}x_i + \sum_{i < j} \tilde{J}_{f(i), f(j)} x_i x_j + \delta_{\mathrm{QUBO}}. \]
Deprecated:
use interaction_matrix()
Parameters
indices
Returns
corresponding interaction matrix (Eigen)
References cimod.model.legacy.binary_quadratic_model::_interaction_matrix.
length()
template<typename IndexType , typename FloatType > size_t cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::length () const inline
Return the number of variables.
Deprecated:
use get_num_variables.
Returns
The number of variables.
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_num_variables().
normalize()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::normalize (const std::pair< FloatType, FloatType > & bias_range = { 1.0, 1.0 }, const bool use_quadratic_range = false, const std::pair< FloatType, FloatType > & quadratic_range = { 1.0, 1.0 }, const std::vector< IndexType > & ignored_variables = {}, const std::vector< std::pair< IndexType, IndexType >> & ignored_interactions = {}, const bool ignored_offset = false) inline
Normalizes the biases of the binary quadratic model such that they fall in the provided range(s), and adjusts the offset appropriately.
Parameters
bias_range
use_quadratic_range
quadratic_range
ignored_variables
ignored_interactions
ignored_offset
remove_interaction()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::remove_interaction (const IndexType & arg_u, const IndexType & arg_v) inline
Remove interaction of variables u, v from a binary quadratic model.
Parameters
arg_u
arg_v
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::remove_variable().
remove_interactions_from()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::remove_interactions_from (const std::vector< std::pair< IndexType, IndexType >> & interactions) inline
Remove all specified interactions from the binary quadratic model.
Parameters
interactions
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::remove_interaction().
remove_offset()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::remove_offset () inline
Set the binary quadratic model's offset to zero.
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::add_offset(), and cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_offset.
remove_variable()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::remove_variable (const IndexType & v) inline
Remove variable v and all its interactions from a binary quadratic model.
Parameters
v
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::remove_interactions_from().
remove_variables_from()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::remove_variables_from (const std::vector< IndexType > & variables) inline
Remove specified variables and all of their interactions from a binary quadratic model.
Parameters
variables
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::remove_variable().
scale()
template<typename IndexType , typename FloatType > void cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::scale (const FloatType & scalar, const std::vector< IndexType > & ignored_variables = {}, const std::vector< std::pair< IndexType, IndexType >> & ignored_interactions = {}, const bool ignored_offset = false) inline
Multiply by the specified scalar all the biases and offset of a binary quadratic model.
Parameters
scalar
ignored_variables
ignored_interactions
ignored_offset
spin_to_binary()
template<typename IndexType , typename FloatType > static std::tuple<Linear<IndexType, FloatType>, Quadratic<IndexType, FloatType>, FloatType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::spin_to_binary (const Linear< IndexType, FloatType > & linear, const Quadratic< IndexType, FloatType > & quadratic, const FloatType & offset) inline static
Convert linear, quadratic, and offset from spin to binary.
Does no checking of vartype. Copies all of the values into new objects.
Parameters
linear
quadratic
offset
Returns
A tuple including a linear bias, a quadratic bias and an offset.
References cimod::insert_or_assign().
to_ising()
template<typename IndexType , typename FloatType > std::tuple<Linear<IndexType, FloatType>, Quadratic<IndexType, FloatType>, FloatType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::to_ising () inline
Convert a binary quadratic model to Ising format.
Returns
A tuple including a linear bias, a quadratic bias and an offset.
References cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::change_vartype(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_linear(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_offset(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_quadratic(), and cimod::SPIN.
to_qubo()
template<typename IndexType , typename FloatType > std::tuple<Quadratic<IndexType, FloatType>, FloatType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::to_qubo () inline
Convert a binary quadratic model to QUBO format.
Returns
A tuple including a quadratic bias and an offset.
References cimod::BINARY, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::change_vartype(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_linear(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_offset(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::get_quadratic(), and cimod::insert_or_assign().
to_serializable()
template<typename IndexType , typename FloatType > json cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::to_serializable () const inline
Convert the binary quadratic model to a serializable object user_bytes is assume to be set to False.
Returns
An object that can be serialized (nlohmann::json)
References cimod::BINARY, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_offset, cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >::m_vartype, and cimod::SPIN.
Member Data Documentation
m_linear
template<typename IndexType , typename FloatType > Linear<IndexType, FloatType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::m_linear protected
Linear biases as a dictionary.
m_offset
template<typename IndexType , typename FloatType > FloatType cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::m_offset protected
The energy offset associated with the model.
m_quadratic
template<typename IndexType , typename FloatType > Quadratic<IndexType, FloatType> cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::m_quadratic protected
Quadratic biases as a dictionary.
m_vartype
template<typename IndexType , typename FloatType > Vartype cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >::m_vartype = Vartype::NONE protected
The model's type.
The documentation for this class was generated from the following file:
binary_quadratic_model_dict.hpp