cimod: cimod.model.legacy.binary_quadratic_model Namespace Reference
cimod.model.legacy.binary_quadratic_model Namespace Reference
Functions
def make_BinaryQuadraticModel (linear, quadratic)
def make_BinaryQuadraticModel_from_JSON (obj)
def BinaryQuadraticModel (linear, quadratic, *args, **kwargs)
Variables
_re_calculate
_re_calculate_indices
_interaction_matrix
_indices
_ind_to_num
vartype
Function Documentation
BinaryQuadraticModel()
def cimod.model.legacy.binary_quadratic_model.BinaryQuadraticModel (linear, quadratic, * args, ** kwargs)
References cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel(), cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel_from_JSON(), and cimod.vartype.to_cxxcimod().
Referenced by cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel().
make_BinaryQuadraticModel()
def cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel (linear, quadratic)
BinaryQuadraticModel factory.
   Generate BinaryQuadraticModel class with the base class specified by the arguments linear and quadratic
Args:
    linear (dict): linear bias
    quadratic (dict): quadratic bias
Returns:
    generated BinaryQuadraticModel class
References cimod.model.legacy.binary_quadratic_model.BinaryQuadraticModel(), and cimod.vartype.to_cxxcimod().
Referenced by cimod.model.legacy.binary_quadratic_model.BinaryQuadraticModel(), and cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel_from_JSON().
make_BinaryQuadraticModel_from_JSON()
def cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel_from_JSON (obj)
References cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel().
Referenced by cimod.model.legacy.binary_quadratic_model.BinaryQuadraticModel().
Variable Documentation
_ind_to_num
cimod.model.legacy.binary_quadratic_model._ind_to_num private
_indices
cimod.model.legacy.binary_quadratic_model._indices private
_interaction_matrix
cimod.model.legacy.binary_quadratic_model._interaction_matrix private
Referenced by cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >.interaction_matrix().
_re_calculate
cimod.model.legacy.binary_quadratic_model._re_calculate private
_re_calculate_indices
cimod.model.legacy.binary_quadratic_model._re_calculate_indices private
vartype
cimod.model.legacy.binary_quadratic_model.vartype
Referenced by cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >.add_interaction(), cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >.add_variable(), cimod::BinaryPolynomialModel< IndexType, FloatType >.AddInteraction(), cimod::BinaryPolynomialModel< IndexType, FloatType >.AddInteractionsFrom(), cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >.change_vartype(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >.change_vartype(), cimod::BinaryPolynomialModel< IndexType, FloatType >.ChangeVartype(), cimod.check_vartype(), cimod.CheckVariables(), cimod.CheckVartypeNotNONE(), cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >.empty(), cimod::BinaryPolynomialModel< IndexType, FloatType >.Empty(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >.empty(), cimod.FormatPolynomialKey(), cimod::BinaryQuadraticModel< IndexType, FloatType, Dict >.from_serializable(), cimod::BinaryQuadraticModel< IndexType, FloatType, DataType >.from_serializable(), and cimod::BinaryPolynomialModel< IndexType, FloatType >.FromSerializable().