cimod: cimod.model.binary_quadratic_model Namespace Reference
cimod.model.binary_quadratic_model Namespace Reference
Functions
def get_cxxcimod_class (linear, quadratic, sparse)
def extract_offset_and_vartype (*args, **kwargs)
def make_BinaryQuadraticModel (linear, quadratic, sparse)
def make_BinaryQuadraticModel_from_JSON (obj)
def BinaryQuadraticModel (linear, quadratic, *args, **kwargs)
def bqm_from_numpy_matrix (mat, list variables=None, offset=0.0, vartype="BINARY", **kwargs)
Variables
model_type
Function Documentation
BinaryQuadraticModel()
def cimod.model.binary_quadratic_model.BinaryQuadraticModel (linear, quadratic, * args, ** kwargs)
References cimod.model.binary_quadratic_model.extract_offset_and_vartype(), and cimod.model.binary_quadratic_model.make_BinaryQuadraticModel().
Referenced by cimod.model.binary_quadratic_model.make_BinaryQuadraticModel().
bqm_from_numpy_matrix()
def cimod.model.binary_quadratic_model.bqm_from_numpy_matrix (mat, list variables = None, offset = 0.0, vartype = "BINARY", ** kwargs)
References cimod.model.binary_quadratic_model.make_BinaryQuadraticModel(), and cimod.model.binary_quadratic_model.make_BinaryQuadraticModel_from_JSON().
extract_offset_and_vartype()
def cimod.model.binary_quadratic_model.extract_offset_and_vartype (* args, ** kwargs)
Referenced by cimod.model.binary_quadratic_model.BinaryQuadraticModel().
get_cxxcimod_class()
def cimod.model.binary_quadratic_model.get_cxxcimod_class (linear, quadratic, sparse)
Referenced by cimod.model.binary_quadratic_model.make_BinaryQuadraticModel().
make_BinaryQuadraticModel()
def cimod.model.binary_quadratic_model.make_BinaryQuadraticModel (linear, quadratic, sparse)
BinaryQuadraticModel factory.
   Generate BinaryQuadraticModel class with the base class specified by the arguments linear and quadratic
Args:
    linear (dict): linear bias
    quadratic (dict): quadratic bias
    sparse (bool): if true, the inner data will be a sparse matrix, otherwise the data will be a dense matrix
Returns:
    generated BinaryQuadraticModel class
References cimod.model.binary_quadratic_model.BinaryQuadraticModel(), cimod.model.binary_quadratic_model.get_cxxcimod_class(), and cimod.vartype.to_cxxcimod().
Referenced by cimod.model.binary_quadratic_model.BinaryQuadraticModel(), cimod.model.binary_quadratic_model.bqm_from_numpy_matrix(), and cimod.model.binary_quadratic_model.make_BinaryQuadraticModel_from_JSON().
make_BinaryQuadraticModel_from_JSON()
def cimod.model.binary_quadratic_model.make_BinaryQuadraticModel_from_JSON (obj)
References cimod.model.binary_quadratic_model.make_BinaryQuadraticModel().
Referenced by cimod.model.binary_quadratic_model.bqm_from_numpy_matrix().
Variable Documentation
model_type
cimod.model.binary_quadratic_model.model_type