cimod: cimod.model.binary_polynomial_model Namespace Reference
cimod.model.binary_polynomial_model Namespace Reference
Classes
class Polynomial
Functions
def make_BinaryPolynomialModel (polynomial, index_type=None, tuple_size=0)
def make_BinaryPolynomialModel_from_JSON (obj)
def BinaryPolynomialModel (*args, **kwargs)
def _BinaryPolynomialModel_from_dict (dict polynomial, vartype)
def _BinaryPolynomialModel_from_list (list keys, list values, vartype)
def make_BinaryPolynomialModel_from_hising (*args, **kwargs)
def _make_BinaryPolynomialModel_from_hising_from_dict (dict polynomial)
def _make_BinaryPolynomialModel_from_hising_from_list (list keys, list values)
def make_BinaryPolynomialModel_from_hubo (*args, **kwargs)
def _make_BinaryPolynomialModel_from_hubo_from_dict (dict polynomial)
def _make_BinaryPolynomialModel_from_hubo_from_list (list keys, list values)
Variables
index_type
model_type
Function Documentation
_BinaryPolynomialModel_from_dict()
def cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_dict (dict polynomial, vartype) private
References cimod.model.binary_polynomial_model.make_BinaryPolynomialModel(), and cimod.vartype.to_cxxcimod().
Referenced by cimod.model.binary_polynomial_model.BinaryPolynomialModel().
_BinaryPolynomialModel_from_list()
def cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_list (list keys, list values, vartype) private
References cimod.model.binary_polynomial_model.make_BinaryPolynomialModel(), and cimod.vartype.to_cxxcimod().
Referenced by cimod.model.binary_polynomial_model.BinaryPolynomialModel().
_make_BinaryPolynomialModel_from_hising_from_dict()
def cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_dict (dict polynomial) private
References cimod.model.binary_polynomial_model.make_BinaryPolynomialModel().
Referenced by cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hising().
_make_BinaryPolynomialModel_from_hising_from_list()
def cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_list (list keys, list values) private
References cimod.model.binary_polynomial_model.make_BinaryPolynomialModel().
Referenced by cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hising().
_make_BinaryPolynomialModel_from_hubo_from_dict()
def cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_dict (dict polynomial) private
References cimod.model.binary_polynomial_model.make_BinaryPolynomialModel().
Referenced by cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hubo().
_make_BinaryPolynomialModel_from_hubo_from_list()
def cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_list (list keys, list values) private
References cimod.model.binary_polynomial_model.make_BinaryPolynomialModel(), cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hising(), cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hubo(), and cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_JSON().
Referenced by cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hubo().
BinaryPolynomialModel()
def cimod.model.binary_polynomial_model.BinaryPolynomialModel (* args, ** kwargs)
References cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_dict(), cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_list(), and cimod.vartype.to_cxxcimod().
Referenced by cimod.model.binary_polynomial_model.make_BinaryPolynomialModel().
make_BinaryPolynomialModel()
def cimod.model.binary_polynomial_model.make_BinaryPolynomialModel (polynomial, index_type = None, tuple_size = 0)
BinaryPolynomialModel factory.
   Generate BinaryPolynomialModel class with the base class specified by the arguments linear and quadratic
Args:
    polynomial (dict): polynomial bias including linear bias
Returns:
    generated BinaryPolynomialModel class
References cimod.model.binary_polynomial_model.BinaryPolynomialModel().
Referenced by cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_dict(), cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_list(), cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_dict(), cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_list(), cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_dict(), cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_list(), and cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_JSON().
make_BinaryPolynomialModel_from_hising()
def cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hising (* args, ** kwargs)
References cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_dict(), and cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hising_from_list().
Referenced by cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_list().
make_BinaryPolynomialModel_from_hubo()
def cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_hubo (* args, ** kwargs)
References cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_dict(), and cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_list().
Referenced by cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_list().
make_BinaryPolynomialModel_from_JSON()
def cimod.model.binary_polynomial_model.make_BinaryPolynomialModel_from_JSON (obj)
References cimod.model.binary_polynomial_model.make_BinaryPolynomialModel().
Referenced by cimod.model.binary_polynomial_model._make_BinaryPolynomialModel_from_hubo_from_list().
Variable Documentation
index_type
cimod.model.binary_polynomial_model.index_type
model_type
cimod.model.binary_polynomial_model.model_type