cimod: cimod.vartype Namespace Reference
cimod.vartype Namespace Reference
Functions
def to_cxxcimod (vartype)
Variables
SPIN = dimod.SPIN
BINARY = dimod.BINARY
Vartype = dimod.Vartype
Function Documentation
to_cxxcimod()
def cimod.vartype.to_cxxcimod (vartype)
Referenced by cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_dict(), cimod.model.binary_polynomial_model._BinaryPolynomialModel_from_list(), cimod.model.binary_polynomial_model.BinaryPolynomialModel(), cimod.model.legacy.binary_quadratic_model.BinaryQuadraticModel(), cimod.model.legacy.binary_quadratic_model.make_BinaryQuadraticModel(), and cimod.model.binary_quadratic_model.make_BinaryQuadraticModel().
Variable Documentation
BINARY
cimod.vartype.BINARY = dimod.BINARY
Referenced by declare_BPM(), and PYBIND11_MODULE().
SPIN
cimod.vartype.SPIN = dimod.SPIN
Referenced by declare_BPM(), and PYBIND11_MODULE().
Vartype
cimod.vartype.Vartype = dimod.Vartype